# Setup
title:            PageTitle
tagline:          'Tagline'
description:      'Longer description'
url:              https://progoza.github.io
baseurl:          '/xyz'
paginate:         5

# About and contact
author:
  name:           'Pawel Rogoza'
  url:            https://progoza.github.io/cv

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
